from django.db import models
# Create your models here.
class users(models.Model):
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    email=models.CharField(max_length=100)
    username=models.CharField(max_length=20)
    password=models.CharField(max_length=30)
class problems(models.Model):
    username=models.CharField(max_length=500, blank=True)
    patient_name=models.CharField(max_length=500, blank=True)
    age=models.CharField(max_length=2, blank=True)
    Address=models.CharField(max_length=500, blank=True)
    fever=models.BooleanField(default=False)
    dry_cough=models.BooleanField(default=False)
    fatigue=models.BooleanField(default=False)
    sputum_production=models.BooleanField(default=False)
    shortness_of_breath=models.BooleanField(default=False)
    mussle_or_joint_pain=models.BooleanField(default=False)
    sore_throat=models.BooleanField(default=False)
    headache=models.BooleanField(default=False)
    chills=models.BooleanField(default=False)
    nausea_or_vomiting=models.BooleanField(default=False)
    nasal_congestion=models.BooleanField(default=False)
    diarrhoea=models.BooleanField(default=False)
    others=models.CharField(max_length=500, blank=True )
    File = models.FileField(upload_to='documents/',null=True,blank=True)
    sendid=models.CharField(max_length=500, blank=True)
    Payment_Proof=models.FileField(upload_to='payments/',null=True, blank=True)

class doctors(models.Model):
    username=models.CharField(max_length=500, blank=True,primary_key = True)
    collage=models.CharField(max_length=500)
    university=models.CharField(max_length=500)
    Passing_Year=models.CharField(max_length=500)
    Experience=models.CharField(max_length=500)
    Upload_Profile_Pic= models.FileField(upload_to='dp/doctors/',null=True,blank=True)
    Degrees=models.CharField(max_length=500)
    Supporting_Document= models.FileField(upload_to='dp/doctors/',null=True,blank=True)
    Home_Address=models.CharField(max_length=500)
    Your_Supporting_Document= models.FileField(upload_to='dp/doctors/',null=True,blank=True)
    Hospital_or_Chamber_Address_1=models.CharField(max_length=500)
    Hospital_or_Chamber_Address_2=models.CharField(max_length=500, blank=True)
    Hospital_or_Chamber_Address_3=models.CharField(max_length=500, blank=True)
    Hospital_or_Chamber_Address_4=models.CharField(max_length=500, blank=True)
    Hospital_or_Chamber_Address_5=models.CharField(max_length=500, blank=True)
    Specialist_of=models.CharField(max_length=500,default='0')
    Fees=models.CharField(max_length=5, blank=True)
    Online_Banking_QR_Code_for_Online_Payment=models.ImageField(upload_to='fees', max_length=100, blank=True)

class nurses(models.Model):
    username=models.CharField(max_length=500, blank=True,primary_key = True)
    collage=models.CharField(max_length=500)
    university=models.CharField(max_length=500)
    Passing_Year=models.CharField(max_length=500)
    Experience=models.CharField(max_length=500)
    Upload_Profile_Pic= models.FileField(upload_to='dp/nurses/',null=True,blank=True)
    Degrees=models.CharField(max_length=500)
    Supporting_Document= models.FileField(upload_to='dp/nurses/',null=True,blank=True)
    Home_Address=models.CharField(max_length=500)
    Your_Supporting_Document= models.FileField(upload_to='dp/nurses/',null=True,blank=True)
class patient(models.Model):
    username=models.CharField(max_length=500, blank=True)
    sugar=models.BooleanField(default=False)
    Sugar_Report=models.FileField(upload_to='patient_Report/',null=True, blank=True)
    pressure=models.BooleanField(default=False)
    Presure_Report=models.FileField(upload_to='patient_Report/',null=True, blank=True)
    heart=models.BooleanField(default=False)
    Heart_Report=models.FileField(upload_to='patient_Report/',null=True, blank=True)
    Any_Operation=models.BooleanField(default=False)
    Report=models.FileField(upload_to='patient_Report/',null=True, blank=True)
    Any_Other_Report=models.FileField(upload_to='patient_Report/',null=True, blank=True)
class usercatagory(models.Model):
    username=models.CharField(max_length=20)
    uses=models.CharField(max_length=80)
class ambulances(models.Model):
    username=models.CharField(max_length=20,blank=True)
    Driver_name=models.CharField(max_length=20)
    Ambulances_Number=models.CharField(max_length=20,primary_key = True)
    Hospital_Belongs_to=models.CharField(max_length=20)
    Upload_Ambulance_Pic=models.ImageField(upload_to='Ambulance/',null=True) 
    Bed_to_Bed_Transfer_Facility=models.BooleanField(default=False)
    emergency_online_support_team=models.BooleanField(default=False)
    Special_care_teams_and_physicians=models.BooleanField(default=False)
    Transfer_the_patient_under_doctors=models.BooleanField(default=False)
    Both_side_road_ambulances=models.BooleanField(default=False)
class hospital(models.Model):
    username=models.CharField(max_length=20,blank=True)
    Hospital_Name=models.CharField(max_length=120,blank=True,primary_key = True)
    Address=models.CharField(max_length=220,blank=True)
    Pictures=models.FileField(upload_to='hospital/photos/',null=True,blank=True)
    Depertment=models.CharField(max_length=20,blank=True)
    Microbiology=models.BooleanField(default=False)
    Pathology=models.BooleanField(default=False)
    Medicine=models.BooleanField(default=False)
    Opthalmology=models.BooleanField(default=False)
    Ostiology=models.BooleanField(default=False)
    Sergery=models.BooleanField(default=False)
    Features=models.CharField(max_length=20,blank=True)
    Bypass_surgery=models.BooleanField(default=False)
    Eye_operation=models.BooleanField(default=False)
    Delivery=models.BooleanField(default=False)
    Dialysis=models.BooleanField(default=False)
    Anjioplasty=models.BooleanField(default=False)
    Chemotherapy=models.BooleanField(default=False)
    Dengue=models.BooleanField(default=False)
    Covid_19_treatment=models.BooleanField(default=False)
class location(models.Model):
    username=models.CharField(max_length=120)
    name=models.CharField(max_length=20)
class doctorresponse(models.Model):
    patient_id=models.CharField(max_length=220)
    doctor_id=models.CharField(max_length=220)
    response=models.CharField(max_length=120)
    abc=models.CharField(max_length=120,blank=True,null=True)
class file2links(models.Model):
    username=models.CharField(max_length=220,blank=True)
    Upload_File=models.FileField(upload_to='file2link')

class chats(models.Model):
    Send_To=models.CharField(max_length=220)
    sender_Id=models.CharField(max_length=220,blank=True)
    msg=models.CharField(max_length=220,blank=True)
    Attatch_File=models.FileField(upload_to='chats')