# Generated by Django 3.0.6 on 2020-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='id',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='username',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
