# Generated by Django 3.0.6 on 2020-06-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
