# Generated by Django 3.0.6 on 2020-06-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='Kind_of_Treatment_Can_Do',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='chills',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='diarrhoea',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='dry_cough',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='fatigue',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='fever',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='headache',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='mussle_or_joint_pain',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='nasal_congestion',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='nausea_or_vomiting',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='others',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='shortness_of_breath',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='sore_throat',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='sputum_production',
        ),
        migrations.RemoveField(
            model_name='nurses',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='username',
            field=models.CharField(blank=True, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Hospital_Name',
            field=models.CharField(blank=True, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='username',
            field=models.CharField(blank=True, max_length=500, primary_key=True, serialize=False),
        ),
    ]
