# Generated by Django 3.0.6 on 2020-06-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctors_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='catagory',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Longitude',
        ),
    ]
