# Generated by Django 3.0.6 on 2020-06-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200609_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='Fees',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
