# Generated by Django 3.0.6 on 2020-06-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctors_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='sendid',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
