# Generated by Django 3.0.6 on 2020-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_problems_sendid'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='Address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='problems',
            name='age',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='problems',
            name='patient_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
