# Generated by Django 3.0.6 on 2020-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200609_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorresponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=220)),
                ('doctor_id', models.CharField(max_length=220)),
                ('response', models.CharField(max_length=120)),
            ],
        ),
    ]
