# Generated by Django 3.0.6 on 2020-06-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctorresponse_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorresponse',
            name='messages',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='doctorresponse',
            name='fees',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
