# Generated by Django 3.0.6 on 2020-06-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200609_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorresponse',
            name='fees',
        ),
        migrations.AddField(
            model_name='doctors',
            name='Online_Banking_QR_Code_for_Online_Payment',
            field=models.ImageField(blank=True, upload_to='fees'),
        ),
    ]
