# Generated by Django 3.0.6 on 2020-06-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200609_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorresponse',
            old_name='messages',
            new_name='message',
        ),
    ]
