# Generated by Django 3.0.6 on 2020-06-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200609_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorresponse',
            old_name='message',
            new_name='messages',
        ),
    ]
