# Generated by Django 3.0.6 on 2020-06-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_doctorresponse_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='file2links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=220)),
                ('Upload_File', models.FileField(upload_to='file2link')),
            ],
        ),
    ]
