# Generated by Django 3.0.6 on 2020-06-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_file2links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file2links',
            name='username',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
