# Generated by Django 3.0.6 on 2020-06-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200610_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorresponse',
            name='messages',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
