# Generated by Django 3.0.6 on 2020-06-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200610_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='Payment_Proof',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
