# Generated by Django 3.0.6 on 2020-06-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_problems_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='Payment_Proof',
            field=models.FileField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
