# Generated by Django 3.0.6 on 2020-06-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200610_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Send_To', models.CharField(max_length=220)),
                ('sender_Id', models.CharField(blank=True, max_length=220)),
                ('Attatch_File', models.FileField(upload_to='chats')),
            ],
        ),
    ]
