# Generated by Django 3.0.6 on 2020-06-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='msg',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
